export class SyncManager {
    constructor(db){ this.db = db; this.base = './api'; }
    getToken(){ return localStorage.getItem('auth_token') || ''; }
    setToken(t){ localStorage.setItem('auth_token', t); }
    async me(){ const token = this.getToken(); if(!token) return null; const r = await fetch(`${this.base}/auth.php?action=me&token=${encodeURIComponent(token)}`,{ headers:{ 'Authorization': `Bearer ${token}` } }); if(!r.ok) return null; const j = await r.json(); return j && j.data ? j.data : null }
    async updateProfileName(name){ const token = this.getToken(); if(!token) return false; const r = await fetch(`${this.base}/auth.php?action=profile&token=${encodeURIComponent(token)}`,{ method:'POST', headers:{ 'Content-Type':'application/json', 'Authorization': `Bearer ${token}` }, body: JSON.stringify({ name }) }); if(!r.ok) return false; const j = await r.json(); return !!(j && j.ok !== false); }
    async updateCredentials(newEmail,newPassword,newName){ const token = this.getToken(); if(!token) return { ok:false, code:401 }; const r = await fetch(`${this.base}/auth.php?action=update&token=${encodeURIComponent(token)}`,{ method:'POST', headers:{ 'Content-Type':'application/json', 'Authorization': `Bearer ${token}` }, body: JSON.stringify({ new_email:newEmail||'', new_password:newPassword||'', new_name:newName||'' }) }); if(!r.ok){ return { ok:false, code:r.status }; } const j = await r.json(); return { ok:true, data:j.data } }
    async emailExists(email){ const r = await fetch(`${this.base}/auth.php?action=exists`,{ method:'POST', headers:{ 'Content-Type':'application/json' }, body: JSON.stringify({ email }) }); if(!r.ok) return false; const j = await r.json(); return !!(j && j.data && j.data.exists); }
    async register(email,password){ const r = await fetch(`${this.base}/auth.php?action=register`,{ method:'POST', headers:{ 'Content-Type':'application/json' }, body: JSON.stringify({ email, password }) }); if (r.status === 409) return { ok:false, exists:true }; return { ok:r.ok } }
    async login(email,password){ const r = await fetch(`${this.base}/auth.php?action=login`,{ method:'POST', headers:{ 'Content-Type':'application/json' }, body: JSON.stringify({ email, password }) }); if(!r.ok) return false; const j = await r.json(); if(j && j.data && j.data.token){ this.setToken(j.data.token); return true; } return false; }
    async pushAll(){ const token = this.getToken(); if(!token) return false; const progress = await this.db.getAllProgress(); const stats = await this.db.getUserStats(); const history = await this.db.getHistory(); const sessions = await (this.db.getAllSessions ? this.db.getAllSessions() : Promise.resolve([])); const payload = { progress: progress.map(p=>({ ...p, updated_at: p.updated_at||0 })), stats: { ...stats, updated_at: stats.updated_at||0 }, history, sessions }; const r = await fetch(`${this.base}/sync.php?action=push&token=${encodeURIComponent(token)}`,{ method:'POST', headers:{ 'Content-Type':'application/json', 'Authorization': `Bearer ${token}` }, body: JSON.stringify(payload) }); if(r.ok){ const ts = Date.now(); await this.db.setProfile('last_sync', ts); } return r.ok; }
    async pullAll(){ const token = this.getToken(); if(!token) return false; if (typeof window !== 'undefined' && window.__disablePull) return false; const r = await fetch(`${this.base}/sync.php?action=pull&token=${encodeURIComponent(token)}`,{ headers:{ 'Authorization': `Bearer ${token}` } }); if(!r.ok) return false; const j = await r.json(); const p = (j.data && j.data.progress) || []; const s = (j.data && j.data.stats) || { xp:0, streak:0, totalQuestions:0, updated_at:0 }; const h = (j.data && j.data.history) || []; const ss = (j.data && j.data.sessions) || []; const resetAt = (j.data && j.data.reset_at) || 0; if (resetAt) await this.db.setProfile('server_reset_at', resetAt); const serverEmpty = (p.length===0) && (h.length===0) && (ss.length===0); if (serverEmpty && this.db.resetProgressOnly) { await this.db.resetProgressOnly(); if (resetAt) await this.db.setProfile('last_reset_ack', resetAt); } else { for(const item of p){ await this.db.saveProgress(item.id,{ id:item.id, level:item.level, nextReview:item.nextReview, correct:item.correct, wrong:item.wrong, updated_at:item.updated_at||0 }); } await this.db.updateUserStats(s); for(const hi of h){ await this.db.logActivity(hi.lesson, hi.unit, !!hi.isCorrect, hi.qid, hi.given_option, hi.cycle_no); } if (ss && ss.length>0 && this.db.importSessions) { await this.db.importSessions(ss); } } const ts = Date.now(); await this.db.setProfile('last_sync', ts); try { document.dispatchEvent(new CustomEvent('app:data-updated')); } catch(e){} return true; }
    async wipeRemote(){ const token = this.getToken(); if(!token) return false; const r = await fetch(`${this.base}/sync.php?action=wipe&token=${encodeURIComponent(token)}`,{ method:'POST', headers:{ 'Authorization': `Bearer ${token}` } }); return r.ok; }
    async deleteAccount(){ const token = this.getToken(); if(!token) return false; const r = await fetch(`${this.base}/auth.php?action=delete&token=${encodeURIComponent(token)}`,{ method:'POST', headers:{ 'Authorization': `Bearer ${token}` } }); if (r.ok){ localStorage.removeItem('auth_token'); return true; } if (r.status === 401){ try { localStorage.removeItem('auth_token'); } catch{} return false; } return false; }

    async autoSync(){ const token = this.getToken(); if(!token) return false; const ok = await this.pushAll(); return ok; }
}
