export class SyncManager {
    constructor(db){ this.db = db; this.base = '/api'; }
    getToken(){ return localStorage.getItem('auth_token') || ''; }
    setToken(t){ localStorage.setItem('auth_token', t); }
    async register(email,password){ const r = await fetch(`${this.base}/auth.php?action=register`,{ method:'POST', headers:{ 'Content-Type':'application/json' }, body: JSON.stringify({ email, password }) }); return r.ok; }
    async login(email,password){ const r = await fetch(`${this.base}/auth.php?action=login`,{ method:'POST', headers:{ 'Content-Type':'application/json' }, body: JSON.stringify({ email, password }) }); if(!r.ok) return false; const j = await r.json(); if(j && j.data && j.data.token){ this.setToken(j.data.token); return true; } return false; }
    async pushAll(){ const token = this.getToken(); if(!token) return false; const progress = await this.db.getAllProgress(); const stats = await this.db.getUserStats(); const history = await this.db.getHistory(); const r = await fetch(`${this.base}/sync.php?action=push`,{ method:'POST', headers:{ 'Content-Type':'application/json', 'Authorization': `Bearer ${token}` }, body: JSON.stringify({ progress, stats, history }) }); return r.ok; }
    async pullAll(){ const token = this.getToken(); if(!token) return false; const r = await fetch(`${this.base}/sync.php?action=pull`,{ headers:{ 'Authorization': `Bearer ${token}` } }); if(!r.ok) return false; const j = await r.json(); const p = (j.data && j.data.progress) || []; const s = (j.data && j.data.stats) || { xp:0, streak:0, totalQuestions:0 }; const h = (j.data && j.data.history) || []; for(const item of p){ await this.db.saveProgress(item.id,{ id:item.id, level:item.level, nextReview:item.nextReview, correct:item.correct, wrong:item.wrong }); } await this.db.updateUserStats(s); for(const hi of h){ await this.db.logActivity(hi.lesson, hi.unit, !!hi.isCorrect); } return true; }
}
